### ISSUE TITLE
Search results in some sort of order

### ISSUE THREAD

**Issue by agryfp** [pixelache/pixelinfra#8]
using pixelache.ac/search 
Search results for "pixelversity:" (which admitedly is probably biggest category)..
yields all related, but in what seems like no order.. I guess there is one somewhere.. but it doesnt seem so useful..

Is it presented according to relevance of word in post?
If dates are supplied is it possible to have them orded temporarily ascending or descending?

I note that the dates of posts are latest edited, rather than original posting date?

**Comment by cenotaph** [comment]
The new search results page now organises by category. It's not really in "order" but at least the content types are separated. Textacular (the search gem I'm using) has its own ranking system as far as I can tell and I'm not sure how configurable it is.

If you think this is OK, close this issue. If you think it's a big problem I can set up a standalone search indexing system.

**Comment by agryfp** [comment]
Looks much better to me, and much easier for someone coming to our pages to find what they are looking for.
